### ISSUE TITLE
Unify test directory

### ISSUE THREAD

**Issue by seanhandley** [fog/fog-openstack#117]
We have two folders, `test` and `tests`.

Really we should unify them.

**Comment by gildub** [comment]
That's the plan.
Test is Minitest, where tests is Shindo, once migration from shindo to minitest is over then tests is going away.
Sorry for not making this more explicit during previous conversations.
Please see comment here: https://github.com/gildub/fog-openstack/blob/master/Rakefile#L15-L16

**Comment by gildub** [comment]
All shindo unit tests have been moved to Minitest with final https://github.com/fog/fog-openstack/pull/177
