### ISSUE TITLE
No tags for release versions > 0.1.2

### ISSUE THREAD

**Issue by voelzmo** [fog/fog-openstack#120]
Hey,
I've noticed that releases above 0.1.2 don't have tags associated in github.
Not sure why that is the case. Maybe that is on purpose so people don't use them?
If not, could you please tag those? Thanks!

**Comment by Ladas** [comment]
we use just tags https://github.com/fog/fog-openstack/tags

That was just one release using github, from that time the release is begin done by rake release.

Do you use github releases for something?

**Comment by voelzmo** [comment]
Thanks @Ladas I guess git tags are completely fine. I was just confused by github's crappy UI which didn't give me a nice diff for the releases.
