### ISSUE TITLE
New minitest suite does ignore FOG_MOCK ENV variable

### ISSUE THREAD

**Issue by petrblaho** [fog/fog-openstack#140]
While doing reviews for "shindont to minitest" PRs I found out that running both
`FOG_MOCK=true SEED=5161 bundle exec rake minitest` and
`FOG_MOCK=false SEED=5161 bundle exec rake minitest` runs the same set of tests despite conditions for `Fog.mocking?` and conditioned `skip`s in tests.

In fact in both cases calling `Fog.mock?` or `Fog.mocking?` returns always `true` and so prevents switching between running tests against mock or against real provider.

This is caused by unconditional `Fog.mock!` at https://github.com/fog/fog-openstack/blob/master/test/test_helper.rb#L14

I think that we should keep option of setting up FOG_MOCK ENV variable working to ensure that we can run tests against real providers.

**Comment by gildub** [comment]
I'm on it.
