### ISSUE TITLE
Set the master branch to protected

### ISSUE THREAD

**Issue by seanhandley** [fog/fog-openstack#15]
@dhague, @Ladas, @mdarby, @jjasghar

I'm setting the master branch to be protected in the repo settings unless anyone has any strong feelings against this.

**Comment by Ladas** [comment]
@seanhandley makes sense (after I've read what protected means :-), no force push )

**Comment by seanhandley** [comment]
Precisely :-)

**Comment by mdarby** [comment]
Good idea. :)
