### ISSUE TITLE
Creating an image with glance hangs at "Queued"

### ISSUE THREAD

**Issue by jockey10** [fog/fog-openstack#151]
Hey all,

I've tried creating an image with Glance using the two examples provided in the README.md. Each time, whether from a file or a URL, the image creation hangs at "Queued", per screenshot:

![screenshot from 2016-06-29 16 35 30](https://cloud.githubusercontent.com/assets/1834999/16442684/9c21bd92-3e17-11e6-8880-7fdcdfc6b9ca.png)

Is anyone else able to replicate this? I can successfully download an image with Glance, just struggling with the upload.

**Comment by Ladas** [comment]
Ah the example is obsolete, for new version of glance, you upload data in a separate step.

Do not send location in the create method, after you create the image, do:

image.upload_data(File.binread(cirros_image_data[:location]))

If it works for you, would you be so kind to update the docs? :-)

**Comment by jockey10** [comment]
Awesome, thanks for the quick reply @Ladas. I'll leave this issue open while I test and update the docs.

**Comment by jockey10** [comment]
All tested successfully, and PR created. I wasn't sure if creating an image from a URL was still supported, or if we have to download the image first and upload using image.upload_data?

**Comment by Ladas** [comment]
@jockey10 I haven't tried creating using URL

**Comment by jockey10** [comment]
No worries - I couldn't get it to work, so I combined the two examples in the PR.

**Comment by muellert** [comment]
I'm on Queens, trying to upload via horizon, and get the same symptom.
