### ISSUE TITLE
get_alarm request is missing an argument

### ISSUE THREAD

**Issue by majewsky** [fog/fog-openstack#155]
In https://github.com/fog/fog-openstack/blob/0189d425a1333d89c9022f68342027ef32a39a2e/lib/fog/openstack/requests/monitoring/get_alarm.rb, an `id` argument is used, but never given.

cc @auhlig @dhague

**Comment by auhlig** [comment]
@majewsky Right. Thanks for finding that. I'll follow up with a fix.
