### ISSUE TITLE
How to specify a network_id when creating a instance

### ISSUE THREAD

**Issue by adamshen** [fog/fog-openstack#176]
I have multiple networks in my cloud.So i get this response error.

> Multiple possible networks found, use a Network ID to be more specific.

**Comment by adamshen** [comment]
i use this connection_params to get the compete, but when i have created a server, it's not belong to the dev. why?
```ruby
@connection_params = {
  openstack_auth_url:     "http://devstack.test:5000/v2.0/tokens"
  openstack_username:     "admin",
  openstack_api_key:      "password",
  openstack_project_name: "dev"
}
```

**Comment by YaEvan** [comment]
@adamshen I met the same question as you. How did you solve this problem? Could you please tell me your solution? Thank you very much.

**Comment by YaEvan** [comment]
@adamshen Did you use create_server instead of create？

**Comment by adamshen** [comment]
@YaEvan Forgive me.It's been so long.I can't remember how i sloved this problem now.

**Comment by YaEvan** [comment]
@adamshen That's all right. Thank you for your reply.

**Comment by YaEvan** [comment]
I solved the problem by ` nics: [{ :net_id => network.id}]` , and here is my code for the people who need it.
`neutron = Fog::Network::OpenStack.new(@connection_params)`

`network = neutron.networks[0]`  // chose you want to use network

`compute.servers.create name: 'Test', image_ref: image.id, flavor_ref: flavor.id, nics: [{ :net_id => network.id}]`
