### ISSUE TITLE
reauthenticate logic should be disabled when only a token is known

### ISSUE THREAD

**Issue by majewsky** [fog/fog-openstack#189]
A `Fog::Something::OpenStack` instance can be constructed without actual credentials, by giving only an auth URL and token. For example:

```ruby
@compute = Fog::Compute::OpenStack.new(
  openstack_auth_url: "https://my.openstack.host:5000/v3/auth/tokens",
  openstack_region: "staging",
  openstack_auth_token: "24f75...",
  openstack_domain_id: "47dfc...",
)
```

When a 401 error is received, `Fog::OpenStack::Core#request` will call into `#authenticate` which will discard the token and attempt to renew the authentication. That obviously fails miserably because no identifying information is left in the options.

The re-authentication logic should therefore be disabled when no username (or user ID) and password have been given.

cc @auhlig

**Comment by Carthaca** [comment]
No, the current https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/core.rb#L41 takes care of that in #request https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/core.rb#L91. Make sure that your service uses the most recent `Fog::OpenStack::Core`.

**Comment by majewsky** [comment]
Okay, thanks.
