### ISSUE TITLE
Starting Ceilometer stops Keystone service

### ISSUE THREAD

**Issue by Rajiv-Chaudhary** [fog/fog-openstack#226]
Hi, 
     I am trying to add ceilometer service to my system  which is already configured with   nova,heat,glance,neutron services. I followed the steps from Installation manual :
http://docs.openstack.org/project-install-guide/telemetry/newton/
The other mentioned services are also installed from this manual.
   
   When I enable ceilometer from apache2 using a2ensite  and run
   ceilometer meter-list command
   I get following error :
   Unable to establish connection to http://01HW478340:35357/v3

   Which means my keystone has stopped ... I reconfirmed it by running nova service-list giving error:
   No handlers could be found for logger "keystoneauth.identity.generic.base"
    ERROR (ConnectFailure): Unable to establish connection to http://01HW478340:35357/v3/auth   
    /tokens

    When i disable ceilometer with dissensite command ..... Keystone starts working again!!!.

    Can anyone let me know what steps I am missing . 
    Thanks in advance

**Comment by seanhandley** [comment]
Hi @Rajiv-Chaudhary,

The `fog-openstack` gem lets you communicate using Ruby with a functioning OpenStack cloud via the APIs it provides. The team that maintains this gem isn't really best placed to provide you with operational support regarding the running of your own OpenStack cloud services.

I recommend you ask for help in the OpenStack IRC channels #openstack-telemetry and #openstack-ceilometer (see https://wiki.openstack.org/wiki/IRC) for more.

For what it's worth, you can run Keystone and Horizon through Apache but you shouldn't need to run Ceilometer using Apache. Maybe you need to change the way you've configured it.

Good luck,
Sean
