### ISSUE TITLE
When i use fog-openstack v0.1.17, i try to run the images method of the nova server api,and it failed.My openstack version is mitaka. anybody knows the reason ?  thanks.

### ISSUE THREAD

**Issue by zhoutiekui** [fog/fog-openstack#248]
When i use fog-openstack v0.1.17, i try to run the images method of the nova server api,and it failed.My openstack version is mitaka. anybody knows the reason ?  thanks.

TestCode:  
p server = @service.servers.get("fe94717a-e4af-4ed6-9aff-c06517f96447")
p @service.images(:server => server)

error log:
Error: test_server_metadata(NovaServersTest):
  NoMethodError: undefined method `server_id' for #<Fog::Compute::OpenStack::I
ge:0x00000002d5f230>
  Did you mean?  server
                 server=

**Comment by seanhandley** [comment]
Hi @zhoutiekui 

Please try `p @service.images.all(:server => server.id)` and let me know if it works.

**Comment by seanhandley** [comment]
Also, please note that the `#images` API support in Nova has been deprecated so you might have more luck using `@service = Fog::Image::OpenStack.new(connection_hash)`

**Comment by zhoutiekui** [comment]
@seanhandley  I followed your guide and  succeed,thank you very much.
