### ISSUE TITLE
Version 0.1.19 ignores image properties in Glance V1

### ISSUE THREAD

**Issue by Kiemes** [fog/fog-openstack#260]
After this change https://github.com/fog/fog-openstack/commit/f654416963bb424c30e37908061fcf90b8459b45 [custom image properties](http://developer.openstack.org/api-ref/image/v1/index.html?expanded=show-image-details-and-image-data-detail#images) get lost when converting the openstack response into an image object when retrieving an image via `images.find_by_id('id')`. e.g. `X-Image-Meta-Property-foo`

Before, those properties where accessible via `image.properties #=> { 'foo' => 'bar' }`, which is now always `nil`.

**Comment by seanhandley** [comment]
I see @Kiemes - this seems to be the kind of breaking change that could be fixed with microversion-aware code (see #242).

In the interim, I suggest writing client code that looks for `properties` and if they turn out to be `nil` then it looks for the required fields by name. The changes I introduced in #253 will take the image properties and extract them to named attributes i.e. `@image.name`, `@image.checksum`, `@image.size` etc

**Comment by voelzmo** [comment]
@seanhandley: I guess the point @Kiemes is making is that your changes in https://github.com/fog/fog-openstack/pull/253 actually broke custom image properties. You're taking `X-Image-Meta-` as prefix, which works for all 'built in' properties, such as `size`, `disk_format`, `name`, and so on. However, users can also set custom properties, which show up in the metadata section of the image. Those have the prefix `X-Image-Meta-property-`, as pointed out by the [documentation](http://developer.openstack.org/api-ref/image/v1/index.html?expanded=show-image-details-and-image-data-detail#images): 
> Custom image properties are returned in headers prefixed by the string x-image-meta-property- (for example, x-image-meta-property-foo).

Now, that means, the following workflow is broken:
* create an image with custom properties `foo` and `bar`
* get the image using `images.find_by_id('id')`
* now the properties on the object are called `property-foo` and `property-bar`

If necessary, we can provide a test for that case. Wdyt?

**Comment by seanhandley** [comment]
Sure - I'd love to see a test case @Kiemes. If anyone would like to get a pull request together too I'm happy to provide assistance 👍

**Comment by voelzmo** [comment]
@seanhandley Here is something I put quickly together to show the problem:
```
require 'fog/openstack'

image = Fog::Image::OpenStack::V1.new({
    :openstack_api_key => ENV['OS_PASSWORD'],
    :openstack_username => ENV['OS_USERNAME'],
    :openstack_auth_url => ENV['OS_AUTH_URL'] + '/auth/tokens',
    :openstack_project_name => ENV['OS_PROJECT_NAME'],
    :openstack_project_id => ENV['OS_PROJECT_ID'],
    :openstack_user_domain => ENV['OS_USER_DOMAIN_NAME'],
    :openstack_endpoint_type => 'publicURL',
    :connection_options => {
        :ssl_verify_peer => false,
        :connect_timeout => 600,
        :read_timeout => 120,
        :write_timeout => 1
    }
})

my_image = image.images.create ({name:  "test-image-properties",
                    disk_format:      "qcow2",
                    container_format: "bare",
                    location:         'cirros-0.3.4-x86_64-disk.img',
                    properties: {"blah": "blubb"}})

loop do
  my_image.reload
  if (my_image.status == "active")
    break
  end
  sleep 5
end
images = image.images
puts "image doesn't contain properties #{images.find_by_id(my_image.id).inspect}"
puts "property is in 'X-Image-Meta-Property-Blah' #{image.get_image(my_image.id).inspect}"
```

It assumes that `OS_` env vars are populated and you did `curl -J -L -O http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img`

**Comment by zeroDivisible** [comment]
Hey folks - I was thinking about fixing this particular bug as (if I understand the nature of it correctly), it may break some of the workflows for me.

I created a pull request - #288 - but because that's my first one here, would be great if somebody could review if I'm not doing anything stupid there.

**Comment by Carthaca** [comment]
https://github.com/fog/fog-openstack/pull/288 merged

**Comment by Kiemes** [comment]
@zeroDivisible thanks, this fixed the issue.
@Carthaca thanks for merging and pinging here
