### ISSUE TITLE
Add support for Barbican Secret ACLs

### ISSUE THREAD

**Issue by ScottMaclure** [fog/fog-openstack#278]
https://docs.openstack.org/developer/barbican/api/reference/acls.html

My Use Cases:

* Allows for project-access = false
* Can add specific Users to a Secret ACL

Would this go into KeyManager?

https://github.com/fog/fog-openstack/blob/master/lib/fog/key_manager/openstack.rb

**Comment by Carthaca** [comment]
Hi @ScottMaclure, yes KeyManager is the right place.

Feel free to implement and send a Pull-request :)
