### ISSUE TITLE
Bad expected return code for update volume metadata request

### ISSUE THREAD

**Issue by shoudusse** [fog/fog-openstack#284]
Hello,
As per the[ openstack documentation](https://developer.openstack.org/api-ref/block-storage/v2/index.html?expanded=create-volume-metadata-detail#create-volume-metadata), the HTTP return code in case of success is 202.
fog-openstack only expect 200 [code](https://github.com/fog/fog-openstack/blob/master/lib/fog/volume/openstack/requests/update_metadata.rb#L12)
I will create a PR to fix this

**Comment by voelzmo** [comment]
That's interesting. We're using this call quite often in our CPI implementation. Looking at the cinder code, I think that the actual return code is 200. Could it be that the documentation is just incorrect?

* https://github.com/openstack/cinder/blob/92980e4972356f16389539b4cc926d7b4ec1dc3c/cinder/api/openstack/wsgi.py#L445
* https://github.com/openstack/cinder/blob/master/cinder/api/v2/volume_metadata.py#L77

**Comment by shoudusse** [comment]
Exact, vanilla Openstack return a 200 while a Huawei FusionSphere OpenStack return a 202

**Comment by voelzmo** [comment]
Not sure if we should pull this in then, or just have the openstack documentation updated. Seems like Huawei needs to bug fix this?

**Comment by Carthaca** [comment]
@shoudusse Can you please address this at Huawei FusionSphere OpenStack?

I merged the additional return code in the meanwhile: practicability over strictness here

**Comment by shoudusse** [comment]
Thanks for the merging.
Huawei FusionSphere OpenStack R&D team is looking for this issue from their side.
