### ISSUE TITLE
[Swift] Updating object metadata results in a GET+PUT

### ISSUE THREAD

**Issue by timuralp** [fog/fog-openstack#289]
fog-openstack exposes object metadata through a `head()` call. However, attempting to update the object metadata results in a GET and then a PUT (as `body` is required in the `save` method and there is no other method that would update the object metadata).

Copy could work in this case, however, it also calls `target_directory.files.get(target_file_key)` at the end of the call. And copy is also not recommended in current Swift releases, in preference of fast-POST (https://wiki.openstack.org/wiki/Swift/ObjectSystemMetadata#.27fast-POST.27).

I'd like to expand the behavior of the file model to issue a POST request to update metadata. For "File" instances created from `head()`, it would be straightforward: detect that there is no body and issue a POST. However, in the case of models created from a GET request, it may be useful to keep track of whether object content is "dirty" and needs to be written back. If this sounds reasonable, I'd be happy to submit a PR.

**Comment by timuralp** [comment]
@geemus I don't know whom to pull in about this, but it looks like the object storage part of OpenStack is a bit abandoned at the moment. This particular bug should be important, although maybe fog users don't use fog with OpenStack Swift? I started on this because I did encounter at least one complaint of metadata updates being a PUT and a re-upload of the object. The storage tests also currently are disabled if FOG_MOCK is set and do not pass otherwise, as they are order dependent.

Do you know who, if anyone, is maintaining this part of the fog-openstack provider?

**Comment by geemus** [comment]
Hey, sorry to hear.

I'm not sure in particular, but maybe somebody on @fog/fog-openstack can help? It's possible that we don't have a clear maintainer, in which case it would fall to me. I'm happy to help in that case, it just feels a bit dangerous as I've never used swift and don't have access to an install (ie I can certainly review in the abstract/code level, but that's about it).

**Comment by timuralp** [comment]
@geemus no problem -- it's understandable. I couldn't quite figure out whom to address with this and the issue has been open for about a month. I figured with the pull request, it makes more sense to start the discussion about how to merge it. I think I'll try to submit a PR to fix the existing tests, so that they can at least pass against a functional Swift cluster. Providing the `FOG_MOCK` support for them would probably be the next step, but that's a bigger undertaking. At least having some set of tests that work should de-risk some of the follow-on work (like the referenced PR).

For what it's worth, there is also the Swift-in-a-Docker container project https://github.com/bouncestorage/docker-swift, which is how I've been testing my work.

**Comment by geemus** [comment]
@timuralp cool, thanks for the update and details. That sounds like a reasonable approach, just let me know if you still don't hear back from anyone else and need me to step in.

**Comment by geemus** [comment]
@timuralp I had kind of forgotten, but another resource would be: https://gitter.im/fog/fog-openstack (I pinged in there, but you might also try as it might help you connect more directly).

**Comment by seanhandley** [comment]
Hi @geemus @timuralp,

PR looks fine to me so I've merged! I find work on this gem happens because people need the changes and so far nobody's really cared much for Swift (personally our company uses the S3 protocol/radosgw to do object storage calls).

If it's something you care about then I'm happy to add you as a contributor so Swift gets the love it needs. Let me know if you're interested.

**Comment by geemus** [comment]
Thanks!

**Comment by timuralp** [comment]
@seanhandley thanks for looking through it/merging!

Seeing how working on Swift and helping our customers use it, I think it would be great for me to able to work on improving the existing support for it in fog. I'd be happy to be a contributor and want to follow up a couple of patches that came up in this conversation: fixing the existing Swift tests to start with.
