### ISSUE TITLE
forcefully destroy/delete cinder volume

### ISSUE THREAD

**Issue by ighouri** [fog/fog-openstack#307]
http://www.rubydoc.info/github/fog/fog-openstack/Fog/Volume/OpenStack/Volume I don't see any method exposed that "forcefully" delete/destroy the  the cinder volume. I can see destroy method only. Can someone please expose that so we forcefully destroy cinder volume through gem fog ?

**Comment by seanhandley** [comment]
Hi @ighouri 

The Fog gem interfaces with the OpenStack API and, as such, we are limited in our abilities by what actions that API makes available. To my knowledge, the destruction of Cinder volumes via the API is as simple as a DELETE HTTP request of this form: https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=delete-a-volume-detail#delete-a-volume

You'll have to explain what you mean by "forcefully" before I can help any further.

**Comment by ighouri** [comment]
@seanhandley 
Thanks for your response. So this is the action I need https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=force-delete-a-volume-detail#force-delete-a-volume
which is a force-delete-a-volume action (and it is a POST request). How I do this through fog ruby gem library as I don't see any available method in above rubydoc link.

**Comment by Carthaca** [comment]
Hi @ighouri 

we only support block-storage v2 right now, nevertheless by https://developer.openstack.org/api-ref/block-storage/v2/?expanded=force-delete-volume-detail#force-delete-volume you can achieve force-deletion through the action request https://github.com/fog/fog-openstack/blob/master/lib/fog/volume/openstack/requests/action.rb, so with something like

```ruby
volume_service = Fog::Volume::OpenStack::V2.new
data = {'os-force_delete' => nil}
uuid = 'ab3c612e-c8e7-4299-9f20-1c6d56628e3f' # openstack uuid of volume to delete
volume_service.action(uuid, data)
```

**Comment by ighouri** [comment]
@Carthaca 
thanks much. 
So here is my script:

`require 'fog'

volume_service = Fog::Volume::OpenStack::V2.new({
  :openstack_api_key => "changeme",
  :openstack_username => "changeme",
  :openstack_tenant => "changeme",
  :openstack_auth_url => "changeme"
}) 

data = {'os-force_delete' => nil}
uuid = '7bb8cc9d-efd0-439a-af35-4e4b85729d3e'
volume_service.action(uuid, data)`

And here is the output:

> /Users/ighouri/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.57.0/lib/excon/middlewares/expects.rb:7:in `response_call': Expected([200, 202]) <=> Actual(403 Forbidden) (Excon::Error::Forbidden)
excon.error.response
  :body          => "{\"forbidden\": {\"message\": \"Policy doesn't allow volume_extension:volume_admin_actions:force_delete to be performed.\", \"code\": 403}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "131"
    "Content-Type"           => "application/json; charset=UTF-8"
    "Date"                   => "Thu, 06 Jul 2017 19:31:48 GMT"
    "X-Compute-Request-Id"   => "req-2f2332f7-cb96-4727-b3f9-afc22f1ac868"
    "X-Openstack-Request-Id" => "req-2f2332f7-cb96-4727-b3f9-afc22f1ac868"
  }

Seems error code 403 (related to permission issue). But same script work (with same volume_service credentials above) if I do
`
volume = volume_service.volumes.get '7bb8cc9d-efd0-439a-af35-4e4b85729d3e'
puts volume.inspect
`

Is it some admin action that not anyone can use ? Any clue ? Thanks again.

**Comment by ighouri** [comment]
@Carthaca 
The reason I am asking because I was able to successfully make a get call (for example get_volume_details https://github.com/fog/fog-openstack/blob/master/lib/fog/volume/openstack/requests/get_volume_details.rb) with same volume_service variable credentials.
`volume = volume_service.get_volume_details('7bb8cc9d-efd0-439a-af35-4e4b85729d3e')
puts volume.inspect
`

**Comment by Carthaca** [comment]
Yes, that means, you are not allowed to perform this action - by the default the policy limits this to admins https://github.com/openstack/cinder/blob/1bf5e884eb8ac33cd1073c601b1279c1af0c7d3b/etc/cinder/policy.json#L60, but your cloud provider could have changed this - ask him what permission you need.

**Comment by ighouri** [comment]
@Carthaca 
awesome. Thats what I was thinking as well as I am not the cloud service admin.

Thanks for the help.
