### ISSUE TITLE
Release v.0.1.22 please... the new OpenStack Pike wants to talk :)

### ISSUE THREAD

**Issue by wildloop** [fog/fog-openstack#315]
The fix [commit/c6906abf357180dfb81a94f3c345393d63da0f33](https://github.com/fog/fog-openstack/commit/c6906abf357180dfb81a94f3c345393d63da0f33) `Remove ".json" extension from Nova API requests` is required for [OpenStack Pike Nova (released: 2017-08-30)](https://releases.openstack.org/pike/).

When the version 0.1.22 will be released?

**Comment by seanhandley** [comment]
Great question. 

I've passed it on to https://gitter.im/fog/fog-openstack (which is a great place to get the attention of the team).

**Comment by Ladas** [comment]
0.1.22 released

**Comment by wildloop** [comment]
Thanks!
