### ISSUE TITLE
Travis gate Ruby 2.2.0 is failing due to a bundler issue

### ISSUE THREAD

**Issue by ioggstream** [fog/fog-openstack#326]
### I expect

Travis Ruby 2.2.0 gate to work 

### Instead
It throws

```
NoMethodError: undefined method `spec' for nil:NilClass

```
See https://travis-ci.org/fog/fog-openstack/jobs/287713712#L1020.

Updating bundler (see #325 ) make the gate work.

**Comment by ioggstream** [comment]
@seanhandley  @Ladas Can you please give some feedback on that? All pull requests  are red for that reason :(

**Comment by Ladas** [comment]
Merged https://github.com/fog/fog-openstack/pull/325, thank you @ioggstream
