### ISSUE TITLE
fog-openstack 0.1.23 incompatible with fog-core 2.0.0

### ISSUE THREAD

**Issue by WalterS** [fog/fog-openstack#368]
When trying to load fog/openstack, I get the following error message:
```
gem require 'fog/openstack'
Gem::ConflictError: Unable to activate fog-openstack-0.1.23, because fog-core-2.0.0 conflicts with fog-core (~> 1.40)
```

**Comment by gildub** [comment]
@WalterS, not sure how you bump it this issue. Maybe try to flush your gems first.

**Comment by WalterS** [comment]
Flushing and updating to fog-openstack 0.1.24 did help, thanks.
