### ISSUE TITLE
Let's promote @aufi to core maintainer

### ISSUE THREAD

**Issue by gildub** [fog/fog-openstack#371]

**Comment by Ladas** [comment]
:+1:

**Comment by gildub** [comment]
@mdarby, @geemus, @plribeiro3000, not sure what's the process, how many votes are required?

**Comment by plribeiro3000** [comment]
Hmm. On other repos there isn't a defined process. If would say that if @aufi is helping and he know the process of pushing everything through PR's and asking others to review just add him. =)

**Comment by geemus** [comment]
Thanks for asking. Sounds great. We don't really have an official process, but as @plribeiro3000 suggests, I think if the existing maintainers think they should be added, we should add them.

I just sent him an invite, thanks!

**Comment by aufi** [comment]
Thanks for adding!
