### ISSUE TITLE
401 Unauthorized: Temp URL invalid 

### ISSUE THREAD

**Issue by fmh** [fog/fog-openstack#372]
I use this gem with paperclip gem to up/download files. everything works fine except the display of files / images, I have this error "401 Unauthorized: Temp URL invalid ", here is my code : 
`````ruby
   storage: :fog,
      fog_credentials: {
          provider: 'OpenStack',
          openstack_region: region,
          openstack_username: username,
          openstack_api_key: password,
          openstack_auth_url: url_auth,
          openstack_project_name: project_name,
          openstack_project_id: project_id,
          openstack_temp_url_key: **key chosen at random** 
  },
 my_file.attachment.expiring_url(Time.now + 30, :thumb) # 401 Unauthorized: Temp URL invalid 
#link generated :
https://cloud_provider_link/v1/my_id/storage_folder/image.png?temp_url_sig=a3121bc7febd184a41be38f7b318c87064c72048&temp_url_expires=1519753004

**Comment by fmh** [comment]
same issue when used with no paperclip gem , only this gem : 
````ruby
connection_params =  {
          provider: 'OpenStack',
          openstack_region: region,
          openstack_username: username,
          openstack_api_key: password,
          openstack_auth_url: url_auth,
          openstack_project_name: project_name,
          openstack_project_id: project_id,
          openstack_temp_url_key: **key chosen at random** 
  }
storage = Fog::Storage.new(connection_params)
temp_url = storage.get_object_https_url("jb007","magnum.png", Time.now + 3600)

#https://cloud_provider_link/v1/my_id/storage_folder/image.png?temp_url_sig=1dc6ed8b516e183b5ca7fb22ed4ff175ed6be515&temp_url_expires=1519765977
````

**Comment by gildub** [comment]
@fmh, could you please provide a bit more about the context, such as the Openstack version you're working with? Also you said "everything works fine except the display of files / images"  and then you mention the `get_object_https_url` issue. Could you clarify what's working and not. Is `get_object` working?

**Comment by fmh** [comment]
@gildub, openstack 3.3.17 , rails 5.1.5 , ruby 2.3.3.
**connection to container/storage and get_object works**. Only get_object_https_url give me a correct url but when I try to use it to download the file I have the following error : 401 Unauthorized: Temp URL invalid.
For example: 
````ruby
temp_url = storage.get_object_https_url("jb007","magnum.png", Time.now + 3600)
#returned url:
#https://cloud_provider_link/v1/my_id/jb007/magnum.png?temp_url_sig=1dc6ed8b516e183b5ca7fb22ed4ff175ed6be515&temp_url_expires=1521401595

**Comment by gildub** [comment]
@fmh, I need to investigate more but I hadn't the bandwidth for it, will try later this week, more likely next one.

**Comment by timuralp** [comment]
@fmh I attempted to reproduce the issue with the code you provided and can't seem to do so. I tried against Swift 2.16 and 2.17 (https in the first case and http in the second). Both tests were successful in a sense that I could generate a tempurl that granted access to the object.

What do you mean by `My container is private`? I'm not sure which provider you're using, however the Swift defaults would not make a container publicly readable. Can you reproduce the issue with docker-swift (https://github.com/bouncestorage/docker-swift) or give pointers on how to do so against some other cloud?

**Comment by gildub** [comment]
Thanks @timuralp. Closing this one then.
@fmh please re-open if you disagree by providing a follow-up.
