### ISSUE TITLE
Keystone cache or TTL ?

### ISSUE THREAD

**Issue by DemisBand** [fog/fog-openstack#387]
Hello,

I have a restriction with my cloud provider which is that I can only generate keystone 60 times per minute. A keystone expires after 24 hours.

Is there the possibility to cache the keystone or set up a TTL?

Here is an example of configuration in a model:

```
has_attached_file: file,
: escape_url => false,
: hash_secret => OPENSTACK_SECRET,
: path => ": class /: attachment /: hash /: basename.: extension",
: storage =>: fog,: fog_credentials => {
: provider => 'OpenStack',
: openstack_auth_url => OPENSTACK_AUTH_URL,
         : openstack_username => OPENSTACK_USERNAME, 
         : openstack_api_key => OPENSTACK_API_KEY, 
         : openstack_region => OPENSTACK_REGION
         },: fog_directory => FOG_DIRECTORY_NEWS
```

thank you,
Thomas.

**Comment by Carthaca** [comment]
Hi Thomas,

you can have a look at the parameter `openstack_cache_ttl`

Cheers

**Comment by DemisBand** [comment]
@Carthaca I will test this, thank you !!
