### ISSUE TITLE
Redundant slash for LIST server's volume attachments API

### ISSUE THREAD

**Issue by TommyLike** [fog/fog-openstack#389]
The first slash in the request url of file [get_server_volumes.rb](https://github.com/fog/fog-openstack/blob/dc635a68a92c62d20adedb0e8dd5f34baa385eb7/lib/fog/compute/openstack/requests/get_server_volumes.rb#L9)

> /servers/#{server_id}/os-volume_attachments

 is redundant and should be removed.

**Comment by zhongjun2** [comment]
@gildub  Cloud we fix this bug in the prior tag versions.

**Comment by TommyLike** [comment]
@zhongjun2  I guess we can't

**Comment by gildub** [comment]
@zhongjun2, @TommyLike is right we can't because we cannot replace existing gem. We could take the same branch as any existing gem, patch but the version can't be the same.

**Comment by zhongjun2** [comment]
@gildub  @TommyLike   I got it. Thanks
