### ISSUE TITLE
Unable to call Volume Services(EVS) SDK by referring fog-openstack example code

### ISSUE THREAD

**Issue by aniketpawar92** [fog/fog-openstack#395]
**Gem version:** 0.1.25

**Issue:**
As given in example code, I am trying to call OpenStack SDK for **volume** services but I am facing issues in establishing the connection. Please correct if I am going wrong while parameter passing.  Also, do check below code snippet and please let me know the correct way to call volume services.
![img1](https://user-images.githubusercontent.com/28944953/41285047-c23ed96a-6e58-11e8-94ac-f638aee4e063.jpg)

**Error:**
![image](https://user-images.githubusercontent.com/28944953/41287549-b193b31c-6e60-11e8-89f1-3818bc8cb55e.png)

**Note:** 
I have called **OpenStack** SDK for **ECS** services and I got success in it.
But, facing issues while calling **EVS** services.

**Comment by gildub** [comment]
@aniketpawar92, could you please describe your auth_url? 

Does it looks like "exmaple.com:5000/v3/auth/tokens"

Also in order to validate your credentials are you able to authenticate (using CURL or OpenStack client) with the same user, project and domain?

**Comment by aniketpawar92** [comment]
@gildub thanks for replay, 

1. I am trying to call **OpenStack Telefonica Native API**. As per your suggestion, I have tried the scenario using **CURL** but, it is giving the following error response for authentication.

![image](https://user-images.githubusercontent.com/28944953/41601377-eb6f7e32-73f5-11e8-8c4e-95037f7c22b1.png)

2. The authentication URL for token generation is
 [https://iam.sa-brazil-1.telefonicaopencloud.com/v3/auth/tokens](https://iam.sa-brazil-1.telefonicaopencloud.com/v3/auth/tokens)

could you please help me out? If I am going wrong.

**Comment by gildub** [comment]
@aniketpawar92,

```bash
export OS_AUTH_URL="http://192.0.2.6:5000/v3/auth/tokens"

export OS_USER=admin
export OS_PASSWORD="password"
export OS_USER_DOMAIN_ID=default

export OS_PROJECT_DOMAIN_ID=default
export OS_PROJECT_NAME=admin

# Note this won't work if there space in any variable (more likely the password), use hard coded value in -d section with more quotes

curl -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "'"${OS_USER}"'",
          "domain": { "id": "'"${OS_USER_DOMAIN_ID}"'" },
          "password": "'"${OS_PASSWORD}"'"
        }
      }
    },
    "scope": {
      "project": {
        "name": "'"${OS_PROJECT_NAME}"'",
        "domain": { "id": "'"${OS_PROJECT_DOMAIN_ID}"'" }
      }
    }
  }
}' \
  ${OS_AUTH_URL} ; echo
```
More details with [those examples](https://docs.openstack.org/keystone/pike/api_curl_examples.html)

**Comment by aniketpawar92** [comment]
**@gildub**,

I already confirmed my authentication using Postman tool for ECS and Volume services. Also, I have called fog-openstack for ECS services and I got success in it.
But, facing issues while calling EVS services.

**Comment by gildub** [comment]
@aniketpawar92 ,

Your output shows fog-openstack 0.1.25, which is latest release but the fog-core version from your log above shows fog-core 1.45.0. That doesn't match our latest release using fog-core 1.40.0. 

So it seems you're using a downstream version and I don't have any visibility of it.

**Comment by aniketpawar92** [comment]
@gildub,

After installing fog-openstack gem when I run **bundle install** command it will automatically install fog-core 1.45.0. As per your suggestion, I installed fog-core 1.40.0 manually and print services from fog/openstack.rb file. Please find the below output:
![img](https://user-images.githubusercontent.com/28944953/41711823-9ec4f6bc-7566-11e8-9ca6-101dcca5c6aa.jpg)

**Comment by aniketpawar92** [comment]
@gildub, Thanks for your quick response. 
After providing openstack_region in my credentials this still shows an error. But this time it shows an error for **Endpoint** i.e. **No endpoint available for region 'sa-brazil-1'**. Please find below output and let me know if I am going wrong.
![img5](https://user-images.githubusercontent.com/28944953/41772534-98cfa394-7636-11e8-9fff-00057bf221da.jpg)

**Comment by gildub** [comment]
@aniketpawar92, apparently you also need to add `:openstack_endpoint_type => 'public'` to your credentials, somehow the default is using 'adminURL'.

**Comment by aniketpawar92** [comment]
@gildub, Still I am facing the same error.

**Comment by gildub** [comment]
Is you environment accessible?

**Comment by aniketpawar92** [comment]
@gildub, sorry my environment is not accessible. But as per your previous comment when I passed :openstack_endpoint_type => '**publicURL**' instead of :openstack_endpoint_type => '**public**', I am able to call **Volume Services**. 
We got this solution by referring the method **self.map_endpoint_type** in lib/fog/openstack.rb. Please verify whether we are following the standard way else we can close this issue.

**Comment by gildub** [comment]
@aniketpawar92, yes I meant 'publicURL', that's it.
