### ISSUE TITLE
support new vnc console api

### ISSUE THREAD

**Issue by easyljy** [fog/fog-openstack#400]
In get_vnc_console.rb, the action **os-getVNCConsole** is deprecated in microversion 2.5 and superseded by the API Server [Remote Consoles](https://developer.openstack.org/api-ref/compute/#server-remote-consoles) in microversion 2.6. The new API offers a unified API for different console types.

**Comment by gildub** [comment]
Issue has been resolved. Thanks @easyljy for spotting it.
