### ISSUE TITLE
fog-core 2+ support to refactor namespace and clear deprecation messages

### ISSUE THREAD

**Issue by gildub** [fog/fog-openstack#431]
We now support fog-core 2+ meanwhile we need to re-factor in order to properly align with it.

All deprecation messages such as:
```ruby
[fog][DEPRECATION] The format Fog::Compute::OpenStack is deprecated
[fog][DEPRECATION] Unable to require fog/openstack/compute
```
require to change all Namespace from `Fog::<Service Name>::OpenStack` to `Fog::OpenStack::<Service Name>`

**Comment by stiller-leser** [comment]
Would it be possible to set a less strict fog dependency, i.e. 2.1.0? I know this is an ancient version, but the deprecation warnings introduced into fog-core in september break a lot tests. Same is currently happening with fog-google.

Also thanks for the great work! It is highly appreciated.

**Comment by ymasson** [comment]
thanks a lot @gildub

**Comment by gildub** [comment]
@stiller-leser, @ymasson, version 0.3.1 is now available.
