### ISSUE TITLE
version 0.3.1 changes APIs

### ISSUE THREAD

**Issue by ideaship** [fog/fog-openstack#434]
I had chef-client test runs break right after fog-openstack 0.3.1 was released. It looks like Fog::Identity::OpenStack and a bunch of other APIs got renamed from 0.3.0 to 0.3.1.

A prominent warning of sorts might be a good idea when breaking APIs.

**Comment by mroach** [comment]
Following semantic versioning, the major version should have been increased to indicate it breaks existing functionality.

The update to 0.2 and/or 0.3 broke our OpenStack integration with Paperclip. Yes, Paperclip is deprecated but a minor version shouldn't break existing functionality.

**Comment by gildub** [comment]
I'm sorry for the inconvenience.

It all started with the need for fog-core 2.1.1 which has a fix to allow fog-openstack to support fog-core 2+. Meanwhile that patch also enforces new namespace convention.
When the service is not available within such namespace it would throw a deprecation warning which multiplied by all services makes the dev/CI very unhappy.

That said a major version is definitely needed to reflect changes as the recent minor version change is not enough but also doesn't cover the big change.

So we now have: 
- v0.3.2 which basically reverts to v0.3.0 while at same time loosening dependency on fog-core 2.1.0+
- v1.0.0 which enforces new namespace.

I hope it helps.

**Comment by mroach** [comment]
It helps a lot. Thanks so much for bumping the major version to reflect the breaking changes! Thanks for the explanation of the `fog-core` compatibility.

**Comment by gildub** [comment]
@ideaship, @mroach, you're welcome. And thanks for bringing this up, the road to fog-core 2+ has been long and tedious and although not an excuse, I made a mistake here.
