### ISSUE TITLE
@connection_options get lost for the authenticate call since 0.2.0

### ISSUE THREAD

**Issue by friegger** [fog/fog-openstack#441]
Connecting to an OpenStack with a custom certificate does not work anymore since 0.2.0, as the @connection_options containing the ca_cert (and other options) are not handed to the auth call anymore.

The commit changing this behaviour: https://github.com/fog/fog-openstack/commit/67e5204b7470d37bd6c58aa869a5b8d4f21888fd

**1.0.0:**
https://github.com/fog/fog-openstack/blob/008637a6e4d0f02960b25b4898659a836ec6940a/lib/fog/openstack/core.rb#L209

**0.1.27**:
https://github.com/fog/fog-openstack/blob/c4ccd3319726c935b406eaf32cf339999fa89380/lib/fog/openstack/core.rb#L182

**Comment by gildub** [comment]
@friegger, thank you for reporting this. Actually the @connections_options was still there but not propagated to the new `Auth::Token`.

The following PR is addressing it: https://github.com/fog/fog-openstack/pull/442

**Comment by gildub** [comment]
@friegger , v1.0.1 has been released.
