### ISSUE TITLE
planning.rb: Don't let binding.pry into production, please ^^

### ISSUE THREAD

**Issue by ShamoX** [fog/fog-openstack#469]
I got stuck several times in different contextes on a ligne of `planning.rb`. I made a little search of binding.pry and found it only there. Is there a reason why you let this statement inside published code ?
```shell
$ grep binding.pry -rnB 2 lib
lib/fog/openstack/planning/planning.rb-122-    def self.new(attributes)
lib/fog/openstack/planning/planning.rb-123-      require 'pry-byebug'
lib/fog/openstack/planning/planning.rb:124:      binding.pry
```

I'll prepare a pull request.

**Comment by gildub** [comment]
@ShamoX, this was just a debug stanza left behind. Thanks
