### ISSUE TITLE
Authenticates using passwordCredentials always

### ISSUE THREAD

**Issue by stakach** [fog/fog-openstack#61]
Is there a way to use an API key?
Currently I use the connection param `openstack_api_key: 'password'` and it uses `passwordCredentials` to authenticate, however this isn't always optimal.

I've migrated from the rackspace gem to the openstack as it is easier to work with both rackspace and openstack clouds. However I could use an API key in the rackspace version

**Comment by seanhandley** [comment]
Hi @stakach,

No, you need a username/password pair to authenticate with Keystone then it gives you a token to use for further API calls. There's nothing stopping you from setting your password to something that resembles an API key, though.

**Comment by stakach** [comment]
Yes, you are right. It's a rackspace extension.
Thanks for the clarification :+1:
