### ISSUE TITLE
Support Neutron floating IP addresses

### ISSUE THREAD

**Issue by mdarby** [fog/fog-openstack#69]
https://github.com/rackerlabs/dxeng/issues/68

**Comment by seanhandley** [comment]
That link's a 404 @mdarby

**Comment by seanhandley** [comment]
Also, what exactly do you mean?

We have requests written for CRUD operations on floating IPs i.e. https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/requests/network/create_floating_ip.rb and there's a corresponding model at https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/models/network/floating_ip.rb

**Comment by mdarby** [comment]
Ah, sorry -- that link must belong to a private Rackspace repo. Also, I didn't realize floating IPs were already supported! Less work for me! 

Thanks :)

**Comment by seanhandley** [comment]
My favourite kind of issue :tada:
