### ISSUE TITLE
Bump fog-core to >=1.38.0

### ISSUE THREAD

**Issue by voelzmo** [fog/fog-openstack#83]
To include excon 0.49.0 we need fog-core >=1.38.0. Can we please get a bump to fix https://github.com/excon/excon/issues/542 as described in https://github.com/fog/fog-core/issues/184?

Thanks!

**Comment by voelzmo** [comment]
Thanks @gildub for the quick reaction! Can we also get a release including the bumped dependency?

**Comment by gildub** [comment]
@voelzmo, you're welcome!
I suppose you mean bump the gem version too?

**Comment by voelzmo** [comment]
Yup, that's what I meant.

**Comment by gildub** [comment]
Ok, we need to ask some of the gem maintainers, I'm not on the admin list.
